import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import { Inter, Poppins } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const localData = {
  headerData: {
    logo: {
      media_path: "/Images/logo.png",
      media_alt: "Logo Alt Text",
    },
    links: [
      { href: "/", label: "Home" },
      { href: "/", label: "Products" },
      { href: "/", label: "About" },
      { href: "/", label: "Contact" },
      { href: "/", label: "Blog" },
      { href: "/", label: "Dashboard" },
      { href: "/", label: "Cart" },
    ],

    MobileLinks: [
      { href: "/login", label: "Login" },
      { href: "/register", label: "Register" },
    ],
  },


  footerData: {
    logo: {
      media_path: "/Images/logo.png",
      media_alt: "Logo Alt Text",
    },
    address: `<p>
            123 Business Street <br />
            Trichur, Kerala, India <br />
            PIN: 680001
          </p>`,

    socilaMedia: [
      {
        icon: "/Images/social-fb.svg",
        link: "https://www.facebook.com/myapp",
        title: "Facebook",
      },
      {
        icon: "/Images/social-youtube.svg",
        link: "https://youtube.com",
        title: "Youtube",
      },
      {
        icon: "/Images/social-insta.svg",
        link: "https://www.instagram.com/myapp",
        title: "Instagram",
      },
      {
        icon: "/Images/social-linkedin.svg",
        link: "https://www.linkedin.com/myapp",
        title: "Linkedin",
      },
    ],
    email: "support@myapp.com",
    phone: "+91 98765 43210",

    footerLinks: [
      {
        title: "Company",
        links: [
          { label: "About Us", href: "/" },
          { label: "Careers", href: "/" },
          { label: "Blog", href: "/" },
        ]
      },
      {
        title: "Support",
        links: [
          { label: "Contact", href: "/" },
          { label: "Help Center", href: "/" },
          { label: "Privacy Policy", href: "/" },
        ]
      }
    ]
  }
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body className="flex flex-col min-h-screen">
        <Header data={localData?.headerData} />
        <main className="flex-grow">{children}</main>
        <Footer data={localData?.footerData} />
      </body>
    </html>
  );
}
